'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import AnalysisCharts from '@/components/analysis-charts';

export default function StudentDetailPage() {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<{
    summary: string;
    mechanism: string;
    analogy: string;
    keyPoints: string[];
    visuals?: string;
  } | null>(null);
  const [loading, setLoading] = useState(false);
  const [micActive, setMicActive] = useState(false);
  const [timer, setTimer] = useState(10);
  const timerRef = (useState<number | null>(null))[0] as unknown as { current: number | null };

  // microphone for question input
  const handleMicClick = () => {
    if (!('webkitSpeechRecognition' in window)) {
      alert('Speech recognition is not supported in this browser.');
      return;
    }
    setMicActive(true);
    setTimer(10);
    const recognition = new (window as any).webkitSpeechRecognition();
    recognition.lang = 'en-US';
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;
    let speechRecognized = false;

    // countdown
    let intervalId = window.setInterval(() => {
      setTimer(prev => {
        if (prev <= 1) {
          clearInterval(intervalId);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    const timeoutId = window.setTimeout(() => {
      if (!speechRecognized) {
        recognition.stop();
        setMicActive(false);
        clearInterval(intervalId);
        alert('No speech is recognized');
      }
    }, 10000);

    recognition.onresult = (event: any) => {
      speechRecognized = true;
      clearTimeout(timeoutId);
      clearInterval(intervalId);
      setMicActive(false);
      setTimer(10);
      const transcript = event.results[0][0].transcript;
      setQuestion(transcript);
    };

    recognition.onerror = (event: any) => {
      clearTimeout(timeoutId);
      clearInterval(intervalId);
      setMicActive(false);
      setTimer(10);
      if (event.error === 'not-allowed') {
        alert('Microphone access denied. Please enable microphone permissions in your browser.');
      } else {
        alert('Speech recognition error: ' + event.error);
      }
    };

    recognition.onend = () => {
      // ensure UI is reset if recognition ends without result
      setMicActive(false);
      setTimer(10);
      clearInterval(intervalId);
    };

    recognition.start();
  };

  const handleAsk = async () => {
    if (!question.trim()) return;
    setLoading(true);
    setAnswer(null);
    try {
      const res = await fetch('/api/ai/answer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question }),
      });
      const data = await res.json();
      if (data && data.summary) {
        setAnswer(data);
      } else if (data.error) {
        setAnswer({ summary: data.error, mechanism: '', analogy: '', keyPoints: [] });
      } else {
        setAnswer({ summary: 'No answer', mechanism: '', analogy: '', keyPoints: [] });
      }
    } catch (err) {
      setAnswer({ summary: 'Request failed', mechanism: '', analogy: '', keyPoints: [] });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-gray-50/50 p-4">
      <div className="max-w-3xl w-full">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle>Medical Student — Deep Explanations</CardTitle>
            <CardDescription>Ask for deeper explanations, analogies, and learning visuals generated by the AI.</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="mb-4">Sample prompts: "Explain how metformin works with an analogy" or "Show learning steps for identifying adverse drug reactions"</p>
            <div className="flex items-start gap-2">
              <Textarea placeholder="Ask a question for the AI (e.g., explain drug mechanism)" value={question} onChange={(e) => setQuestion(e.target.value)} />
              <div className="flex flex-col items-center">
                <button
                  type="button"
                  onClick={handleMicClick}
                  disabled={micActive}
                  aria-label="Speak your question"
                  className={`p-2 rounded-full border border-gray-300 hover:bg-gray-100 ${micActive ? 'bg-blue-100 border-blue-400' : ''}`}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 18v3m0 0a6 6 0 0 0 6-6v-3a6 6 0 0 0-12 0v3a6 6 0 0 0 6 6zm0-9v6" /></svg>
                </button>
                {micActive && (
                  <span className="text-sm text-blue-600 font-semibold mt-2">Listening... {timer}s</span>
                )}
              </div>
            </div>
            <div className="mt-4 flex gap-2">
              <Button onClick={handleAsk} disabled={loading || !question.trim()}>{loading ? 'Asking...' : 'Ask AI'}</Button>
              <Button variant="ghost" onClick={() => { setQuestion(''); setAnswer(null); }}>Clear</Button>
            </div>

            {answer && (
              <div className="mt-4">
                <h4 className="font-semibold mb-2">AI Answer</h4>
                <div className="bg-card p-4 rounded">
                  <h5 className="font-semibold">Summary</h5>
                  <p className="mb-2">{answer.summary}</p>

                  <h5 className="font-semibold">Mechanism</h5>
                  {answer.mechanism.split('\n\n').map((p, i) => (
                    <p key={i} className="mb-2">{p}</p>
                  ))}

                  <h5 className="font-semibold">Analogy</h5>
                  <blockquote className="border-l-4 pl-3 italic text-muted-foreground">{answer.analogy}</blockquote>

                  {answer.keyPoints && answer.keyPoints.length > 0 && (
                    <>
                      <h5 className="font-semibold mt-3">Key Points</h5>
                      <ul className="list-disc list-inside mt-1">
                        {answer.keyPoints.map((kp, idx) => (
                          <li key={idx}>{kp}</li>
                        ))}
                      </ul>
                    </>
                  )}

                  {answer.visuals && (
                    <>
                      <h5 className="font-semibold mt-3">Suggested Visual</h5>
                      <p className="text-sm text-muted-foreground">{answer.visuals}</p>
                    </>
                  )}

                  <div className="mt-4">
                    <h5 className="font-semibold">Further reading</h5>
                    <ul className="list-disc list-inside mt-2 text-sm space-y-1">
                      <li><a className="text-primary hover:underline" href="https://medlineplus.gov/druginformation.html" target="_blank" rel="noreferrer">MedlinePlus — Drug information</a></li>
                      <li><a className="text-primary hover:underline" href="https://www.fda.gov/drugs" target="_blank" rel="noreferrer">FDA — Drug safety and labels</a></li>
                      <li><a className="text-primary hover:underline" href="https://www.bmj.com/" target="_blank" rel="noreferrer">BMJ — Clinical resources for students</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            )}

            <div className="mt-6">
              <Card>
                <CardHeader>
                  <CardTitle>Visualizations</CardTitle>
                  <CardDescription>Simple charts based on your most recent interaction check.</CardDescription>
                </CardHeader>
                <CardContent>
                  <AnalysisCharts />
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
